name: User Story (Core Maintainers Only)
description: Describe a user problem and the intended outcome
labels:
  - "user-story"
body:
  - type: markdown
    attributes:
      value: |
        This template is for **user stories in the product repo**.
        It captures **product intent and outcomes**, not implementation details.
        It does not imply prioritization, scheduling, or implementation commitment.
        
  - type: textarea
    id: need
    attributes:
      label: User Need
      description: >
        What problem is being solved? What is currently missing, unclear, or difficult?
        Please avoid proposing solutions.
      placeholder: >
        Example Need:
        People living in a small village without access to a car have very limited
        mobility. Without a reliable way to travel beyond the village, it is difficult
        to access jobs, education, healthcare, or social opportunities outside the
        immediate area.
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goal(s)
      description: >
        What should be possible once this story is addressed?
        Describe outcomes, not features or implementation.
      placeholder: |
        Example Goals:
        - People without cars can travel beyond the village and explore the outside world
        - Fewer residents need to rely on individual car trips for daily travel
        - Traffic congestion in and around the village is reduced
        - Air quality improves due to lower vehicle emissions
    validations:
      required: true

  - type: textarea
    id: non_goals
    attributes:
      label: Non-Goals / Out of Scope
      description: >
        What is explicitly not being addressed as part of this story?
      placeholder: |
        Example Non-Goals:
        - Optimizing routes or schedules
        - Ticket pricing or fare systems
        - Long-distance or inter-city transport
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: >
        Concrete examples or analogies that help clarify the need or goals.
      placeholder: |
        Code examples, existing implementations, or other relevant context.
    validations:
      required: false
