name: User Story
description: Describe a user problem or need that may result in product work
title: "[Story] "
labels:
  - user-story
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        ## User Story

        This template is for **user problems or needs**, not implementation proposals.
        If you are reporting a bug, documentation issue, or proposing a technical design,
        please use the appropriate template instead.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Need
      description: >
        What problem is the user experiencing? What is hard, confusing, or impossible today?
        Describe the problem without proposing a solution.
      placeholder: >
        Users cannot reliably understand how related records behave when records are deleted,
        leading to data loss or broken assumptions.
    validations:
      required: true

  - type: textarea
    id: user
    attributes:
      label: Affected Users
      description: >
        Who is experiencing this problem? (personas, roles, usage context)
      placeholder: >
        Application developers building on the core database library.
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Why This Matters
      description: >
        Why is this problem worth solving? What impact does it have on users or the ecosystem?
      placeholder: >
        Unclear behavior increases support load and reduces trust in the library for
        production use.
    validations:
      required: true

  - type: textarea
    id: success
    attributes:
      label: Desired Outcome (Success Criteria)
      description: >
        What would be true for the user if this problem were addressed?
        Describe outcomes, not features.
      placeholder: >
        Developers can predict and reason about relation behavior without reading source code.
    validations:
      required: true

  - type: textarea
    id: non_goals
    attributes:
      label: Out of Scope / Non-Goals
      description: >
        What is explicitly not being attempted here? (optional but recommended)
      placeholder: >
        This does not attempt to design a UI or change unrelated APIs.
    validations:
      required: false

  - type: textarea
    id: rfc
    attributes:
      label: RFC Consideration
      description: >
        Does this potentially affect core behavior, public APIs, or long-term direction?
        If yes, note that an RFC may be required.
      placeholder: >
        This likely affects core relation semantics and may require an RFC.
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: Related Context / Links
      description: >
        Link to related issues, discussions, RFCs, or external references.
      placeholder: >
        - #123
        - rfcs/0123-relations-lifecycle.md
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Notes**
        - This story does not imply prioritization or commitment.
        - Implementation details belong in linked issues or RFCs.
        - Product facilitates triage; maintainers advise on technical impact.